forum/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  # Go to home/index by default
  root 'home#index'
  # About page
  get '/about' => 'home#about'

  # post '/questions' => 'home#temp'
  # post '/answers' => 'home#temp'

  # get '/questions/:id' => 'home#question'
end

forum/app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

forum/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

forum/app/models/question.rb
require 'digest'

class Question < ApplicationRecord
    has_many :answers
    
    def gravatar
        "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}?d=robohash"
    end
end

forum/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    question = Question.find(params[:id])
    
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:email, :body, :question_id)
    end
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

forum/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end
  def about
  end
  def temp
    redirect_to root_path
  end
end

forum/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:email, :body)
    end
end

forum/app/helpers/answers_helper.rb
module AnswersHelper
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/home_helper.rb
module HomeHelper
end

forum/app/helpers/questions_helper.rb
module QuestionsHelper
end

forum/app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

forum/app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

forum/app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.email %></td>
        <td><%= answer.body %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

forum/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

forum/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @answer.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

forum/app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CA Brisbane Forum</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a></form></li>
      </ul>
    </div>
  </div>
</nav>

forum/app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Provide an answer</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="answer[body]" id="inputQuestion" placeholder="What is your answer?" required></textarea>
            </div>
          </div>
        </div>
        <input type="hidden" name="answer[question_id]" value="<%=@question.id %>" />
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="Submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

forum/app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ask a question</h4>
      </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="question[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="Submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

forum/app/views/home/about.html.erb
<h1>About</h1>
<p>This forum is used to ask questions of the CA Brisbane cohort</p>

forum/app/views/home/index.html.erb
<h1>CA Brisbane Forum</h1>
<p>Welcome to the Brisbane Coder Academy Forum</p>

<%# media from bootstrap %>
<% for question in @questions%>
    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
            <img class="media-object" src=<%= question.gravatar %> >
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><%= question.email %></h4>
            <p><%= time_ago_in_words(question.created_at) %></P>
            <%= question.body %>
        <div>
            <a href="<%= question_path(question) %>" class="btn btn-success btn-xs">View Answers</a>
        </div>    
    </div>
<% end %>

<%# 
<div class="media">
    <div class="media-left media-middle">
        <a href="#">
        <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">user@email.com asked:</h4>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
    <div>
        <a href="/questions/12" class="btn btn-success btn-xs">View Answers</a>
    </div>    
</div>

<div class="media">
    <div class="media-left media-middle">
        <a href="#">
        <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">user@email.com asked:</h4>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
    <div>
        <a href="/questions/12" class="btn btn-success btn-xs">View Answers</a>
    </div>    
</div> %>

forum/app/views/home/question.html.erb
<div class="lead well">
    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
            <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">user@email.com asked:</h4>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.   
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
        </div>
        <%# render the answer model%>
        <%=render 'home/new_answer_form'%>

        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
    </div>
</div>

forum/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CA Brisbane Forum</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%# Use bootstrap %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# from bootstrap %>
  <div class="container">
    <%= render 'home/navbar' %>
    <%= yield %>
    <%= render 'home/new_question_form'%>
  </div>
  </body>
</html>

forum/app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

forum/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

forum/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.email %></td>
        <td><%= question.body %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

forum/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

forum/app/views/questions/show.html.erb
<div class="lead well">
    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
            <img class="media-object" src=<%= @question.gravatar %> >
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><%= @question.email %></h4>
            <%= @question.body %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
        </div>
        <%# render the answer model%>
        <%=render 'home/new_answer_form'%>

        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <img class="media-object" src="http://www.gravatar.com/avatar/424242" >
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">user@email.com answered:</h4>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, expedita. Ullam voluptatem suscipit, modi corrupti assumenda fugiat a qui ex dolorum, architecto nulla quia accusantium, vitae consectetur cum doloribus debitis.
                
        </div>
    </div>
</div>